# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-26 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frijay', '0002_reservation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=80, unique=True),
        ),
    ]
