# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-01 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frijay', '0002_reservation_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='phone',
            field=models.BigIntegerField(verbose_name='Phone'),
        ),
    ]
